config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
  }
  namespace :admins do
    # get 'top' => 'homes#top', as: 'top'
    # get 'search' => 'homes#search', as: 'search'
    # get 'customers/:customer_id/orders' => 'orders#index', as: 'customer_orders'
    # resources :customers, only: [:index, :show, :edit, :update]
    resources :games
    # resources :genres, only: [:index, :create, :edit, :update]
    # resources :orders, only: [:index, :show, :update] do
    #   resources :order_details, only: [:update]
    # end
  end
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
  }

    scope module: :users do
      get 'users/mypage/:id' => 'users#mypage', as: 'mypage'
      # get 'users/information/:id' => 'users#show', as: 'show_user'
      get 'users/mypage/edit' => 'users#edit', as: 'edit_mypage'
      patch 'users/mypage' => 'users#update', as: 'update_mypage'
      put 'users/mypage' => 'users#update'
      # post 'users/comment' => 'comments#create', as: 'user_comments'
      # delete 'users/comment/:id' => 'comments#destroy', as: 'user_comment'
      resources :users, only: [:index] do
        #ユーザへのコメント
        resources :comments, only: [:create, :destroy]
        #フォロー関係
        resource :relationships, only: [:create, :destroy]
          get 'followings' => 'relationships#followings', as: 'followings'
          get 'followers' => 'relationships#followers', as: 'followers'
        #いいね関係
        resource :favorites, only: [:create, :destroy]
      end

      resources :games, only: [:index, :show]
      # resources :items, only: [:index, :show] do
      #   resources :cart_items, only: [:create, :update, :destroy]
      # end
      # resources :orders, only: [:new, :index, :create, :show]

      # resource :relationships, only: [:create, :destroy]
      #   get 'followings' => 'relationships#followings', as: 'followings'
      #   get 'followers' => 'relationships#followers', as: 'followers'
    end

      root 'homes#top'
      get 'about' => 'homes#about'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :image
  has_many :games
  has_many :game_users, dependent: :destroy
  has_many :favorites, dependent: :destroy
  # カリキュラム４章
  # def favorited_by?(user)
  #   favorites.where(user_id: user.id).exists?
  # end

  #ユーザへのコメント機能についてのリレーション
  has_many :reverse_of_comments, class_name: "Comment", foreign_key: "commented_id", dependent: :destroy
  has_many :comments, class_name: "Comment", foreign_key: "commenter_id", dependent: :destroy
  # 【class_name:"Comment"】は省略可能

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  # 被フォロー関係を通じて参照→followed_idをフォローしている人
  
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 【class_name: "Relationship"】は省略可能
  has_many :followings, through: :relationships, source: :followed
  # 与フォロー関係を通じて参照→follower_idをフォローしている人

  #relationshipsのコントローラにて使用
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  def following?(user)
    followings.include?(user)
  end

validates :name,:email, presence: true

end

app/controllers/users/comments_controller.rb
class Users::CommentsController < ApplicationController
  def create
    user = User.find(params[:user_id])
    comment = Comment.new(comment_params)
    comment.score = Language.get_data(comment.comment)
    comment.commenter_id = current_user.id
    comment.commented_id = user.id
    comment.save
    redirect_to mypage_path(user)
  end

  def destroy
  end

  private

  def comment_params
    params.require(:comment).permit(:comment)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/games_controller.rb
class Users::GamesController < ApplicationController
  def index
    @games = Game.page(params[:page]).per(8)
  end

  def show
    @game = Game.find(params[:id])
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  
  #deviseのストロングパラメータ
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :image_id, :introduction])
  end

 #ログイン後ログアウト後の遷移用必要？
  def after_sign_up_path_for(resource)
    root_path
  end

  def after_update_path_for(resource)
    mypage_path
  end
  
end

app/controllers/users/relationships_controller.rb
class Users::RelationshipsController < ApplicationController
  # ——————フォロー機能を作成・保存・削除する————————————
  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end

  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer  
  end
#————————フォロー・フォロワー一覧を表示する-————————————
  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  #ログイン後ログアウト後の遷移ページ
  def after_sign_in_path_for(resource)
    mypage_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  #ユーザの退会機能実装予定
  # def reject_inactive_user
  #   @user = User.find_by(email: params[:user][:email])
  #   if @user
  #     if @user.valid_password?(params[:user][:password]) && !@user.is_active
  #       flash[:danger] = 'お客様は退会済みです。申し訳ございませんが、別のメールアドレスをお使いください。'
  #       redirect_to new_user_session_path
  #     end
  #   end
  # end

end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/users_controller.rb
class Users::UsersController < ApplicationController
  def mypage
    @user = User.find(params[:id])
    @comment = Comment.new
  end

  # def mypage
  #   @user = current_user
  #   @comment = Comment.new
  # end

  def edit
    @user = current_user
  end

	def update
    @user = current_user
	  if @user.update(user_params)
	    flash[:success] = "登録情報を変更しました"
	    redirect_to mypage_path(@user)
	  else
	    render :edit
	  end
	end

	private

  def user_params
    params.require(:user).permit(:name, :email, :introduction, :image)
  end
end

app/helpers/users/comments_helper.rb
module Users::CommentsHelper
end

app/helpers/users/games_helper.rb
module Users::GamesHelper
end

app/helpers/users/relationships_helper.rb
module Users::RelationshipsHelper
end

app/helpers/users/users_helper.rb
module Users::UsersHelper
end

app/views/users/users/edit.html.erb
<% if @user.errors.any? %>
  <%= @user.errors.count %>件のエラーが発生しました
  <% @user.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<body>
  <div class = "container my-5">
    <div class="row">
      <div class="col offset-2">
        <h3 class="">会員情報編集</h3>
      </div>
    </div>
    <%= form_for(@user, url: update_information_path) do |f| %>
    <div class='row offset-1'>
      <div class="col-xs-offset-1 col-xs-8">
        <%#= form_with model: @user, url: update_information_path, local:true do |f| %>
          <table class = 'table inin'>
          <!--user情報を入れる　テキストフィールド展開-->
          <tr>
            <td>
            <%= attachment_image_tag @user, :image, :fill, 100, 100, fallback: "no_image.jpg"%>
            </td>
          </tr>
          <tr>
            <td>
              <label for="inputImage">イメージ画像</label>
              <%= f.attachment_field :image, placeholder: "プロフィール画像" %>
            </td>
          </tr>
          <tr>
            <td><%= f.label :名前 %></td>
            <td><%= f.text_field :name, :size => "20*30", class: "border border-dark rounded" %></td>
          </tr>
          <tr>
            <td><%= f.label :メールアドレス %></td>
            <td><%= f.text_field :email, :size => "20*30", class: "border border-dark rounded" %></td>
          </tr>
          <tr>
            <td><%= f.label :紹介文 %></td>
            <td><%= f.text_field :introduction, :size => "40*90", class: "border border-dark rounded" %></td>
          </tr>
        </table>
        <!--各リンク先のパスを入れる-->
      </div>
    </div>
          <div class="row">
            <div class="col-sm-2 offset-3">
              <%= f.submit '編集内容を保存', class: 'btn btn-success' %>
            </div>
            <div class="col-sm-2 offset-1">
              <%#= link_to '退会する', customer_confirm_path(current_customer),class: 'btn btn-danger' %>
        <% end %>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>
</body>

app/views/users/users/mypage.html.erb
<main>
  <div class="container my-5">
    <div class="row">
      <div class="col-sm-2">
        <h2>MY PAGE</h2>
      </div>
    </div>
    <div class="row my-3">
      <div class="col-sm-2">
        <h3>登録情報</h3>
      </div>
      <div class="col-sm-2">
        <%= link_to '編集する', edit_mypage_path, class: "btn btn-success px-3"%>
      </div>
    </div>
    <div class='row'>
      <div class="col-sm-7">
        <table class='table border'>
          <tr>
            <td class='information border bg-light'>ユーザー画像</td>
            <td><%= attachment_image_tag @user, :image, size: '60x60', format: 'jpeg', fallback: "no_image.jpg" %></td>
          </tr>
          <tr>
            <td class='information border bg-light'>名前</td>
            <td><%= @user.name %></td>
          </tr>
          <tr>
            <td class='information border bg-light'>メールアドレス</td>
            <td><%= @user.email %></td>
          </tr>
          <tr>
            <td class='information border bg-light'>紹介文</td>
            <td><%= @user.introduction %></td>
          </tr>
        </table>
        <div class="col-sm-10">
          <h3 class="fas fa-users text-left">コミュニケーション情報</h3>
        </div>
        <div>
          <%= link_to "フォローユーザ一覧", user_followers_path(current_user.id) %>
          <%= link_to "フォロワーユーザ一覧", user_followings_path(current_user.id) %>
          <% if current_user.following?(@user) %>
            <%= link_to "フォロー解除する", user_relationships_path(@user.id), method: :delete %>
          <% else %>
            <%= link_to "このユーザをフォローする", user_relationships_path(@user.id), method: :post %>
        </div>
          <% end %>
        <div class="comments">
          <p>コメント件数：<%= @user.comments.count %></p>
          <% @user.comments.each do |comment| %>
            <%= attachment_image_tag comment.commenter, :image, size: '60x60', format: 'jpeg', fallback: "no_image.jpg" %>
            <%= comment.commenter.name %>
            <p class="sentiment-score">本文の感情分析スコア[<%= comment.score %>]</p>
            <%= comment.created_at.strftime('%Y/%m/%d') %><%= comment.comment %>
          <% end %>
        </div>
        <div class="new-comment">
        <%= form_with(model:[@user, @comment], local: true) do |f| %>
          <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに" %>
          <%= f.submit "送信する" %>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/users/users/show.html.erb
<main>
  <div class = "container my-5 ">
    <div class="row">
      <div class="col-sm-2">
        <h2>MY PAGE</h2>
      </div>
    </div>
    <div class="row my-3">
      <div class="col-sm-2">
        <h3>登録情報</h3>
      </div>
      <div class="col-sm-2">
        <%= link_to '編集する', edit_information_path, class: "btn btn-success  px-3"%>
      </div>
    </div>
    <div class='row '>
      <div class="col-sm-7 ">
        <table class = 'table border'>
          <tr>
            <td class = 'information border bg-light'>ユーザー画像</td>
            <td><%= attachment_image_tag @user, :image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %></td>
          </tr>
          <tr>
            <td class = 'information border bg-light'>名前</td>
            <td><%= @user.name %></td>
          </tr>
          <tr>
            <td class = 'information border bg-light'>メールアドレス</td>
            <td><%= @user.email %></td>
          </tr>
          <tr>
            <td class = 'information border bg-light'>紹介文</td>
            <td><%= @user.introduction %></td>
          </tr>
        </table>
        <div class="col-sm-10">
          <h3 class="fas fa-users text-left">コミュニケーション情報</h3>
        </div>
        <div>
          <%= link_to "フォローユーザ一覧", user_followers_path(current_user.id) %>
          <%= link_to "フォロワーユーザ一覧", user_followings_path(current_user.id) %>
          <% if current_user.following?(@user) %>
            <%= link_to "フォロー解除する", user_relationships_path(@user.id), method: :delete %>
          <% else %>
            <%= link_to "このユーザをフォローする", user_relationships_path(@user.id), method: :post %>
        </div>
          <% end %>
        <div class="comments">
          <p>コメント件数：<%= @user.comments.count %></p>
          <% @user.comments.each do |comment| %>
            <p><%= image_tag('no_image.jpg') %></p>
            <%= comment.commenter.name %>
            <%= comment.created_at.strftime('%Y/%m/%d') %><%= comment.comment %>
          <% end %>
        </div>
        <div class="new-comment">
        <%= form_with(model:[@user, @comment], local: true) do |f| %>
          <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに" %>
          <%= f.submit "送信する" %>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</main>