config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
  }
  namespace :admins do
    # get 'top' => 'homes#top', as: 'top'
    # get 'search' => 'homes#search', as: 'search'
    # get 'customers/:customer_id/orders' => 'orders#index', as: 'customer_orders'
    # resources :customers, only: [:index, :show, :edit, :update]
    resources :games
    # resources :genres, only: [:index, :create, :edit, :update]
    # resources :orders, only: [:index, :show, :update] do
    #   resources :order_details, only: [:update]
    # end
  end
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
  }

    scope module: :users do
      get 'users/mypage/:id' => 'users#mypage', as: 'mypage'
      # get 'users/information/:id' => 'users#show', as: 'show_user'
      get 'users/mypage/edit' => 'users#edit', as: 'edit_mypage'
      patch 'users/mypage' => 'users#update', as: 'update_mypage'
      put 'users/mypage' => 'users#update'
      # post 'users/comment' => 'comments#create', as: 'user_comments'
      # delete 'users/comment/:id' => 'comments#destroy', as: 'user_comment'
      resources :users, only: [:index] do
        #ユーザへのコメント
        resources :comments, only: [:create, :destroy]
        #フォロー関係
        resource :relationships, only: [:create, :destroy]
          get 'followings' => 'relationships#followings', as: 'followings'
          get 'followers' => 'relationships#followers', as: 'followers'
        #いいね関係
        resource :favorites, only: [:create, :destroy]
      end

      resources :games, only: [:index, :show]
      # resources :items, only: [:index, :show] do
      #   resources :cart_items, only: [:create, :update, :destroy]
      # end
      # resources :orders, only: [:new, :index, :create, :show]

      # resource :relationships, only: [:create, :destroy]
      #   get 'followings' => 'relationships#followings', as: 'followings'
      #   get 'followers' => 'relationships#followers', as: 'followers'
    end

      root 'homes#top'
      get 'about' => 'homes#about'
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :comments
  attachment :game_image
  
  validates :game_title,:game_image,:game_introduction, presence: true
end

app/controllers/admins/games_controller.rb
class Admins::GamesController < ApplicationController
    before_action :authenticate_admin!

  def index
    @games = Game.all
  end

  def show
    @game = Game.find(params[:id])
    # @game.genre.name
    # genre = Genre.find(1)
    # genre.games # no method error
  end

  def new
    @new_game = Game.new
  end

  def create
    @game = Game.new(game_params)
    if @game.save
      flash[:notice] = "新しいゲームを登録しました"
      redirect_to admins_game_path(@game.id)
    else
      flash[:notice] = "新しいゲームの登録に失敗しました"
      redirect_back(fallback_location: root_path)
    end
  end


  def update
    @game = Game.find(params[:id])
    if @game.update(game_params)
       flash[:notice] = "ゲーム情報を更新しました"
       redirect_to admins_game_path(@game)
    else
       flash[:notice] = "ゲーム情報の更新に失敗しました"
       redirect_back(fallback_location: root_path)
    end
  end

  def edit
    @game = Game.find(params[:id])
  end

  def destroy
    @game = Game.find(params[:id])
    @game.destroy
    redirect_to admins_games_path
  end

  private
  def game_params
    params.require(:game).permit(:game_title, :game_image, :game_introduction)
  end
end

app/controllers/users/games_controller.rb
class Users::GamesController < ApplicationController
  def index
    @games = Game.page(params[:page]).per(8)
  end

  def show
    @game = Game.find(params[:id])
  end
end

app/helpers/admins/games_helper.rb
module Admins::GamesHelper
end

app/helpers/users/games_helper.rb
module Users::GamesHelper
end

app/views/admins/games/edit.html.erb
<div class="container my-5">
  <p id="notice text-success"><%= notice %></p>
  <div class="row">
    <h1>ゲーム編集</h1>
  </div>
  <div class="row">
    <%= form_with model: @game, url: admins_game_path, method: :patch, local:true do |f| %>
    <table class="table">
      <tbody>
        <tr>
          <td>ゲーム画像</td>
          <td><%= f.attachment_field :game_image %></td>
        </tr>
        <tr>
          <td>ゲームタイトル</td>
          <td><%= f.text_field :game_title %></td>
        </tr>
        <tr>
          <td>ゲーム説明</td>
          <td><%= f.text_area :game_introduction %></td>
        </tr>
        <tr>
          <td>ランク</td>
          <td>
          <%#= f.collection_select :genre_id, Genre.all, :id, :name, prompt: "ジャンルを選択してください" %>
          </td>
        </tr>
      </tbody>
    </table>
    <%= f.submit '変更を保存',  class: "btn btn-success" %>
    <% end %>
  </div>
</div>

app/views/admins/games/index.html.erb
<div class="container mb-2">
  <p id="notice text-success"><%= notice %></p>
  <div class="row my-5">
    <div class="col-sm-2 offset-1 d-flex justify-content-center text-dark">
      <h2>ゲーム一覧</h2>
    </div>
    <div class="col offset-6">
      <%= link_to new_admins_game_path do %>
        <h1 class="maru border rounded-circle text-body">＋</h1>
      <% end %>
    </div>
  </div>
  <div class="row">
    <table class="table">
      <thead class="bg-light text-dark">
        <tr>
          <th>ゲームID</th>
          <th>ゲームタイトル</th>
          <th>ランク</th>
          <!--<th>ステータス</th>-->
        </tr>
      </thead>
      <tbody>
        <% @games.each do |game| %>
        <tr>
          <td><%= game.id %></td>
          <td>
            <%= link_to admins_game_path(game) do %>
            <%= game.game_title %>
            <% end %>
          </td>
          <td><%#= item.genre.name %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
  <div class="mb-4 d-flex justify-content-center">
    <%#= paginate(@items) %>
  </div>

app/views/admins/games/new.html.erb
<div class="container my-5">
  <p id="notice"><%= notice %></p>
  <div class="row">
    <h1>新規登録</h1>
  </div>
  <div class="row">
    <%= form_with model: @new_game, url: admins_games_path, local:true do |f| %>
    <table class="table">
      <tbody>
        <tr>
          <td>ゲーム画像</td>
          <td><%= f.attachment_field :game_image %></td>
        </tr>
        <tr>
          <td>ゲームタイトル</td>
          <td><%= f.text_field :game_title, placeholder: "ゲーム名" %></td>
        </tr>
        <tr>
          <td>ゲーム説明</td>
          <td><%= f.text_area :game_introduction, placeholder: "ここに説明文を記述します" %></td>
        </tr>
        <tr>
          <td>ランク</td>
          <td>
            <%#= f.collection_select :genre_id, Genre.all, :id, :name, prompt: "タイトルを選択してください" %>
          </td>
        </tr>
      </tbody>
    </table>
    <%= f.submit '新規登録',  class: "btn btn-success" %>
    <% end %>
  </div>
</div>

app/views/admins/games/show.html.erb
<div class="container my-5">
  <p id="notice text-success"><%= notice %></p>
  <h2>ゲーム詳細</h2>
  <div class="row">
    <div class="col"><%= attachment_image_tag(@game, :game_image, :fill, 500, 300,  fallback: "no_image.jpeg", size:'500x300') %></div>
    <div class="col">
      <table class="table">
        <tbody>
          <tr>
            <td>ゲーム名</td>
            <td><%= @game.game_title %></td>
          </tr>
          <tr>
            <td>ゲーム説明</td>
            <td><%= @game.game_introduction %> </td>
          </tr>
          <tr>
            <td>ランク</td>
            <td><%#= @game.rank.rank_name %></td>
          </tr>
        </tbody>
      </table>
      <%= link_to "編集する", edit_admins_game_path(@game), class: "btn btn-success"%>
      <%= link_to "削除する", admins_game_path(@game), class: "btn btn-danger", method: :delete %>
    </div>
  </div>
</div>