config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
  }
  namespace :admins do
    # get 'top' => 'homes#top', as: 'top'
    # get 'search' => 'homes#search', as: 'search'
    # get 'customers/:customer_id/orders' => 'orders#index', as: 'customer_orders'
    # resources :customers, only: [:index, :show, :edit, :update]
    resources :games
    # resources :genres, only: [:index, :create, :edit, :update]
    # resources :orders, only: [:index, :show, :update] do
    #   resources :order_details, only: [:update]
    # end
  end
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
  }

    scope module: :users do
      get 'users/mypage/:id' => 'users#mypage', as: 'mypage'
      # get 'users/information/:id' => 'users#show', as: 'show_user'
      get 'users/mypage/edit' => 'users#edit', as: 'edit_mypage'
      patch 'users/mypage' => 'users#update', as: 'update_mypage'
      put 'users/mypage' => 'users#update'
      # post 'users/comment' => 'comments#create', as: 'user_comments'
      # delete 'users/comment/:id' => 'comments#destroy', as: 'user_comment'
      resources :users, only: [:index] do
        #ユーザへのコメント
        resources :comments, only: [:create, :destroy]
        #フォロー関係
        resource :relationships, only: [:create, :destroy]
          get 'followings' => 'relationships#followings', as: 'followings'
          get 'followers' => 'relationships#followers', as: 'followers'
        #いいね関係
        resource :favorites, only: [:create, :destroy]
      end

      resources :games, only: [:index, :show]
      # resources :items, only: [:index, :show] do
      #   resources :cart_items, only: [:create, :update, :destroy]
      # end
      # resources :orders, only: [:new, :index, :create, :show]

      # resource :relationships, only: [:create, :destroy]
      #   get 'followings' => 'relationships#followings', as: 'followings'
      #   get 'followers' => 'relationships#followers', as: 'followers'
    end

      root 'homes#top'
      get 'about' => 'homes#about'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commenter, class_name: "User"
  belongs_to :commented, class_name: "User"
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :comments
  attachment :game_image
  
  validates :game_title,:game_image,:game_introduction, presence: true
end

app/models/game_user.rb
class GameUser < ApplicationRecord
  belongs_to :user
  belongs_to :rank
end

app/models/install.rb
class Install < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/rank.rb
class Rank < ApplicationRecord
  belongs_to :game_user
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :image
  has_many :games
  has_many :game_users, dependent: :destroy
  has_many :favorites, dependent: :destroy
  # カリキュラム４章
  # def favorited_by?(user)
  #   favorites.where(user_id: user.id).exists?
  # end

  #ユーザへのコメント機能についてのリレーション
  has_many :reverse_of_comments, class_name: "Comment", foreign_key: "commented_id", dependent: :destroy
  has_many :comments, class_name: "Comment", foreign_key: "commenter_id", dependent: :destroy
  # 【class_name:"Comment"】は省略可能

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  # 被フォロー関係を通じて参照→followed_idをフォローしている人
  
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 【class_name: "Relationship"】は省略可能
  has_many :followings, through: :relationships, source: :followed
  # 与フォロー関係を通じて参照→follower_idをフォローしている人

  #relationshipsのコントローラにて使用
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  def following?(user)
    followings.include?(user)
  end

validates :name,:email, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @games = Game.all.order(created_at: :desc).first(2)
  end
  
  def about
  end
end

app/controllers/users/games_controller.rb
class Users::GamesController < ApplicationController
  def index
    @games = Game.page(params[:page]).per(8)
  end

  def show
    @game = Game.find(params[:id])
  end
end

app/controllers/users/users_controller.rb
class Users::UsersController < ApplicationController
  def mypage
    @user = User.find(params[:id])
    @comment = Comment.new
  end

  # def mypage
  #   @user = current_user
  #   @comment = Comment.new
  # end

  def edit
    @user = current_user
  end

	def update
    @user = current_user
	  if @user.update(user_params)
	    flash[:success] = "登録情報を変更しました"
	    redirect_to mypage_path(@user)
	  else
	    render :edit
	  end
	end

	private

  def user_params
    params.require(:user).permit(:name, :email, :introduction, :image)
  end
end

app/helpers/admins/games_helper.rb
module Admins::GamesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users/comments_helper.rb
module Users::CommentsHelper
end

app/helpers/users/games_helper.rb
module Users::GamesHelper
end

app/helpers/users/users_helper.rb
module Users::UsersHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>E-コミュ</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark">
      <div class="container">
        <%= link_to root_path do %>
          <%= image_tag 'logo.png', width: '40%', height: '40%' %>
        <% end %>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <% if admin_signed_in? %>
              <li><%= link_to 'ゲーム一覧', admins_games_path, class: "btn btn-light border border-dark text-warning mr-1" %></li>
              <li><%#= link_to '会員一覧', admin_users_path, class: "btn btn-light border border-dark text-warning mr-1" %></li>
              <li><%#= link_to 'ランク管理', admin_ranks_path, class: "btn btn-light border border-dark text-warning mr-1" %></li>
              <li><%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class: "btn btn-light border border-dark text-warning mr-1" %></li>
            <% elsif user_signed_in? %>
                <p>ようこそ、<%= current_user.name %>さん!</p>
                <li><%= link_to 'マイページ', mypage_path(current_user.id), class: "btn btn-light border border-dark text-warning mr-1" %></li>
                <li><%= link_to 'ゲーム一覧', games_path, class: "btn btn-light border border-dark text-warning mr-1" %></li>
                <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "btn btn-light border border-dark text-warning mr-1" %></li>
            <% else %>
              <li><%= link_to 'About', about_path, class: "btn btn-light border border-dark text-warning mr-1" %></li>
              <li><%= link_to 'ゲーム一覧', games_path, class: "btn btn-light border border-dark text-warning mr-1" %></li>
              <li><%= link_to '新規登録', new_user_registration_path, class: "btn btn-light border border-dark text-warning mr-1" %></li>
              <li><%= link_to 'ログイン', new_user_session_path, class: "btn btn-light border border-dark text-warning mr-1" %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <main>
      <%= yield %>
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    </main>

 
    <footer>
      <div class='container mt-4'>
        <div class='row d-flex justify-content-center'>
          <div class='d-flex align-items-center'>
            <p class="pr-2 text-primary bg-white border border-dark">Prsent From Famitikiclub</p>
          </div>
        </div>
      </div>
      <div class='container mt-0'>
        <div class='row d-flex justify-content-end'>
          <div class='d-flex align-items-center fa-lg'>
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome-animation/0.0.10/font-awesome-animation.css" type="text/css" media="all" />
            <!--<a class="fab fa-facebook-square faa-wrench animated-hover" href="https://www.facebook.com/"></a>-->
            <!--<a class="fab fa-twitter-square faa-wrench animated-hover" href="https://twitter.com/"></a>-->
            <!--<a class="fab fa-instagram faa-wrench animated-hover" href="https://www.instagram.com/"></a>-->
          </div>
        </div>
      </div>
    </footer>
    
    
    
  </body>
</html>